defmodule Pramana.Docs.Sync do
  @moduledoc """
  Rewrites the generated figure blocks in documentation, and says whether they were stale.

  A block is delimited by comments that are invisible in rendered Markdown:

      <!-- figures:corpus -->
      | | |
      |---|---|
      | texts | 17,281 |
      <!-- /figures -->

  Everything between the markers is generated by `Pramana.Docs.Figures` and everything
  outside them is prose nobody generates. **Editing inside a block is pointless rather
  than forbidden** — the next run overwrites it, and the check fails until then, which is
  the same bargain `mix format` offers.

  ## Why markers rather than a scan

  A scanner that found numbers in prose and checked them would have to understand which
  numbers are corpus counts, which are measurements true of a date, and which are Taishō
  work numbers. It would be wrong constantly and people would learn to ignore it. Markers
  make the claim explicit: a figure inside one is generated and cannot go stale; a figure
  outside one is a person's assertion and carries the usual obligation to date it.

  This does mean an unmarked figure is still unchecked. That is a real limit and the
  moduledoc of `Pramana.Docs.Figures` states it — the mechanism removes a class of
  staleness, it does not remove staleness.
  """

  # ANCHORED TO ITS OWN LINE, and that is not cosmetic. Unanchored, this matched the
  # marker syntax quoted INSIDE `docs/CHECKS.md`'s explanation of the mechanism, and the
  # gate failed with `{:unknown_block, "key"}` because the sentence said `figures:key`.
  # A tool that cannot survive being documented is a tool nobody can document.
  @open ~r/^<!-- figures:(?<key>[a-z_]+) -->$/m
  @close "<!-- /figures -->"

  @doc "Every document holding at least one generated block."
  @spec documents(String.t()) :: [String.t()]
  def documents(root) do
    root
    |> Path.join("docs/*.md")
    |> Path.wildcard()
    |> Enum.filter(&(File.read!(&1) =~ @open))
    |> Enum.sort()
  end

  @doc """
  The document's content with every block regenerated, and the keys that changed.

  Returns `{:error, {:unknown_block, key}}` rather than leaving a marker unfilled: a block
  nothing generates is a promise the file makes and the code does not keep, which is worse
  than no block at all.
  """
  @spec rewrite(String.t(), %{String.t() => [{String.t(), String.t()}]}) ::
          {:ok, String.t(), [String.t()]} | {:error, term()}
  def rewrite(content, blocks) do
    content
    |> String.split(@open, include_captures: true, trim: false)
    |> rebuild(blocks, [], [])
  end

  defp rebuild([], _blocks, acc, changed),
    do: {:ok, acc |> Enum.reverse() |> Enum.join(), Enum.reverse(changed)}

  defp rebuild([chunk | rest], blocks, acc, changed) do
    case Regex.named_captures(@open, chunk) do
      %{"key" => key} -> replace_block(key, chunk, rest, blocks, acc, changed)
      _ -> rebuild(rest, blocks, [chunk | acc], changed)
    end
  end

  defp replace_block(key, marker, [body | rest], blocks, acc, changed) do
    with {:ok, figures} <- fetch_block(blocks, key),
         {:ok, old, tail} <- split_at_close(body, key) do
      new = "\n" <> table(figures) <> @close
      changed = if old <> @close == new, do: changed, else: [key | changed]
      rebuild(rest, blocks, [tail, new, marker | acc], changed)
    end
  end

  defp replace_block(key, _marker, [], _blocks, _acc, _changed),
    do: {:error, {:unterminated_block, key}}

  defp fetch_block(blocks, key) do
    case Map.fetch(blocks, key) do
      {:ok, figures} -> {:ok, figures}
      :error -> {:error, {:unknown_block, key}}
    end
  end

  defp split_at_close(body, key) do
    case String.split(body, @close, parts: 2) do
      [old, tail] -> {:ok, old, tail}
      [_unterminated] -> {:error, {:unterminated_block, key}}
    end
  end

  defp table(figures) do
    rows = Enum.map_join(figures, "\n", fn {label, value} -> "| #{label} | **#{value}** |" end)
    "| | |\n|---|---|\n" <> rows <> "\n"
  end
end
