import Config

# Configure your database
config :pramana, Pramana.Repo,
  username: System.get_env("PGUSER") || System.get_env("USER"),
  password: System.get_env("PGPASSWORD") || "",
  hostname: System.get_env("PGHOST") || "localhost",
  database: "pramana_dev",
  # Bake tasks insert tens of thousands of rows; per-query logging buries the
  # actual output. Set PRAMANA_SQL_LOG=1 to get it back when debugging.
  log: System.get_env("PRAMANA_SQL_LOG") == "1" and :debug,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # Sized for the bake, not for a web request. Loading one work is a single
  # transaction that can insert 26,000+ rows (T1912 is the largest in the Taisho), and
  # the default 15s checkout timeout kills exactly those — 26 of 2,471 works failed
  # this way, every one of them large. Timeouts here are a capacity problem, never a
  # data problem, so raise capacity rather than shrink the transaction.
  #
  # 120s was enough until a work spanning volumes became ONE transaction: assembled
  # X1571 is 74,570 lines against T1912's 26,000, and it timed out at 120s. Raising the
  # ceiling is the fix the rule above prescribes — splitting the load would put half a
  # work in the corpus if the second half failed, which is the defect that made the
  # assembly necessary in the first place.
  pool_size: 25,
  timeout: 300_000,
  queue_target: 5_000,
  queue_interval: 30_000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pramana_web, PramanaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "nzFEBTu6TE+zzsl/cxxm6k2soEGUnNTDQoysm2l9PpeUfXXva8wEk/qgjSSj3ksJ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pramana_web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pramana_web, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :pramana_web, PramanaWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/pramana_web/router\.ex$"E,
      ~r"lib/pramana_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pramana_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
